target-version = "py311"
select = [
    "B",
    "C4",
    "E7",
    "E9",
    "EXE",
    "I",
    "ICN",
    "W",
    "F",
    "PT",
    "RUF",
    "SIM",
    "UP",
]
ignore = [
    # Unused imports, might never be able to fix properly
    "F401",
    # TODO: Fix mutable function argument defaults
    "B006",
    # TODO: Fix return inside finally block
    "B012",
    # TODO: Fix comparison to None with ==
    "E711",
    # TODO: Fix comparison to True with ==
    "E712",
    # TODO: Fix raising inside exception handler
    "B904",
    # TODO: Useless comparison
    "B015",
    # TODO: pytest stuff without autofix
    "PT004",
    "PT005",
    "PT007",
    "PT011",
    "PT012",
    "PT015",
    "PT018",
    # never enable, we use specific unicode characters intentionally
    "RUF001",
    # TODO: flatten if conditions
    "SIM102",
    # TODO: use contextlib.suppress
    "SIM105",
    # TODO: use file open context manager
    "SIM115",
]

[isort]
force-single-line = true
